### ISSUE TITLE
proposal: move `main` package into `cmd/asdf` and rename module for compatibility with `go install`

### ISSUE THREAD

**Issue by DeedleFake** [asdf-vm/asdf-core-go#84]
### Is your feature request related to a problem? Please describe

Installing the new Go version is a bit strangely roundabout, especially for a Go CLI tool.

### Describe the proposed solution

The convention for Go projects is to put `main` packages in a subdirectory of `cmd` named the same as what the output binary should be so that they can be easily installed with, for example, `go install github.com/asdf-vm/asdf-core-go/cmd/asdf@latest`. This would also make it possible to keep ASDF up to date via, for example, [gup](https://github.com/nao1215/gup) as a replacement for the removed `asdf update` command.

The module name will also need to be updated to follow Go conventions, changing from `asdf` to `github.com/asdf-vm/asdf-core-go`.

### Describe similar `asdf` features and why they are not sufficient

`asdf update` is being removed in the Go rewrite.

### Describe other workarounds you've considered

N/A.

**Comment by Stratus3D** [comment]
Hi @DeedleFake , thanks for opening this issue! I'm completely new to Go - this is my first big project in Go. I was not aware of Gup and am in favor of making asdf easy to install with it. Note that most existing users of asdf either follow the manual install instructions (see the asdf website) or use their own package manager (probably `brew` most of the time) to install asdf. That probably won't change once this new Go version is released, but it'd be great to support `go install`/Gup as an additional install method for those that prefer it.

I'd be interested in a PR for this, would you be willing to open one? Alternatively, can you reference other projects that follow the pattern of putting `main` under `cmd`?

**Comment by DeedleFake** [comment]
I might not get to it right away, but I can definitely send a PR when I do get a chance. 

As for other projects that use `cmd`, [`golang.org/x/tools` is structured like that](https://golang.org/x/tools/cmd). It's also recommended by [the official docs](https://go.dev/doc/modules/layout#:~:text=A%20common%20convention,cmd%20directory).

Careful to _not_ follow the conventions in the "Standard Go Project Layout" repo. It's [not actually l standard at all](https://github.com/golang-standards/project-layout/issues/117).

**Comment by Stratus3D** [comment]
Closing as I believe this has been completed.
